//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by HUSTNDT.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_HUSTNDTYPE                  129
#define IDD_DIALOG_INTIALSET            130
#define IDD_DIALOG_MAIN                 131
#define IDD_DIALOG_SHOWSET              132
#define IDD_DIALOG_SETCARD              133
#define IDD_DIALOG_PARSET               134
#define IDD_DIALOG_M_Par                135
#define IDR_ENVIROMENT_MENU             136
#define IDD_DIALOG_DATASET              137
#define IDD_DIALOG_CHOOSEFILE           138
#define IDD_DIALOG_STRPAR               139
#define IDB_BITMAP_CLOSE                140
#define IDB_BITMAP_OPEN                 142
#define IDD_DIALOG_IOSTATUS             143
#define IDD_DIALOG_MSGDLG               144
#define IDD_DIALOG_REPORTS              145
#define IDB_BITMAP_BACKGROUND           148
#define IDD_DIALOG_PRINTREPORT          150
#define IDC_BUTTON_SINGLE               1000
#define IDC_BUTTON_NET                  1001
#define IDC_EDIT_SINGLE                 1002
#define IDC_EDIT_NET                    1003
#define IDC_CHECK_AUTO                  1004
#define IDC_BUTTON_START                1005
#define IDC_BUTTON_STOP                 1006
#define IDC_BUTTON_DEMOCRATE            1007
#define IDC_BUTTON_PARSET               1008
#define IDC_BUTTON_DATABASE             1009
#define IDC_BUTTON_CARDSET              1010
#define IDC_BUTTON_REPORT               1011
#define IDC_BUTTON_SHOWSET              1012
#define IDC_EDIT_MSG                    1014
#define IDC_PROGRESS                    1015
#define IDC_EDIT_HELP                   1016
#define IDC_COMBO_SET1                  1019
#define IDC_COMBO_SET2                  1020
#define IDC_STATIC1                     1021
#define IDC_STATIC2                     1022
#define IDC_STATIC3                     1023
#define IDC_STATIC4                     1024
#define IDC_STATIC5                     1025
#define IDC_STATIC6                     1026
#define IDC_STATIC7                     1027
#define IDC_STATIC8                     1028
#define IDC_BUTTON_OPEN                 1029
#define IDC_RADIO1                      1030
#define IDC_BUTTON_ANALYSIS             1031
#define IDC_RADIO2                      1031
#define IDC_BUTTON_RESHOW               1032
#define IDC_RADIO3                      1032
#define IDC_RADIO4                      1033
#define IDC_COMBO_CARDCHOOSE            1034
#define IDC_RADIO5                      1034
#define IDC_EDIT_SAMPLESPEED            1035
#define IDC_RADIO6                      1035
#define IDC_STATIC_SAMPLESPEED          1036
#define IDC_RADIO7                      1036
#define IDC_EDIT_CHANNELNUM             1037
#define IDC_STATIC_CHANNELNUM           1038
#define IDC_RADIO8                      1038
#define IDC_STATIC_BLOCK                1039
#define IDC_EDIT_BLOCK                  1040
#define IDC_CHECK_CODING                1041
#define IDC_LIST_PAR                    1043
#define IDC_BUTTON_RESET                1045
#define IDC_COMBO_INDEX                 1046
#define IDC_BUTTON_SAVE                 1047
#define IDC_EDIT1                       1048
#define IDC_EDIT2                       1049
#define IDC_EDIT3                       1050
#define IDC_EDIT4                       1051
#define IDC_EDIT5                       1052
#define IDC_EDIT6                       1053
#define IDC_EDIT7                       1054
#define IDC_EDIT8                       1055
#define IDC_BUTTON_RESUME               1057
#define IDC_EDIT_SYSTEMSTARTCH          1058
#define IDC_STATIC_STARTCH              1059
#define IDC_LIST1                       1060
#define IDC_LIST_SHOWCH                 1061
#define IDC_COMBO1                      1062
#define IDC_COMBO2                      1063
#define IDC_BUTTON_DATASAVESET          1063
#define IDC_COMBO3                      1064
#define IDC_COMBO_DATASET               1064
#define IDC_LIST_THR                    1065
#define IDC_EDIT_FILENAME               1065
#define IDC_COMBO4                      1066
#define IDC_EDIT_MAN                    1066
#define IDC_COMBO5                      1067
#define IDC_LIST_BACK                   1067
#define IDC_COMBO6                      1068
#define IDC_LIST_FILENAMELIST           1068
#define IDC_COMBO7                      1069
#define IDC_BUTTON_1p                   1069
#define IDC_EDIT_FIND                   1069
#define IDC_COMBO8                      1070
#define IDC_BUTTON_1n                   1070
#define IDC_BUTTON_2p                   1071
#define IDC_BUTTON_2n                   1072
#define IDC_BUTTON_3p                   1073
#define IDC_BUTTON_3n                   1074
#define IDC_BUTTON_4p                   1075
#define IDC_BUTTON_4n                   1076
#define IDC_BUTTON_5p                   1077
#define IDC_BUTTON_5n                   1078
#define IDC_BUTTON_6p                   1079
#define IDC_BUTTON_6n                   1080
#define IDC_BUTTON_7p                   1081
#define IDC_BUTTON_7n                   1082
#define IDC_BUTTON_8p                   1083
#define IDC_BUTTON_8n                   1084
#define IDC_BUTTON_pp1                  1085
#define IDC_BUTTON_pp2                  1086
#define IDC_BUTTON_pp3                  1087
#define IDC_BUTTON_pp4                  1088
#define IDC_BUTTON_pp5                  1089
#define IDC_BUTTON_pp6                  1090
#define IDC_BUTTON_pp7                  1091
#define IDC_BUTTON_pp8                  1092
#define IDC_BUTTON_allpp                1093
#define IDC_BUTTON_allp                 1094
#define IDC_BUTTON_alln                 1095
#define IDC_BUTTON_allnn                1096
#define IDC_STATIC_CURRENTNUM           1097
#define IDC_EDIT_CURRENTNUM             1098
#define IDC_BUTTON_GONUM                1099
#define IDC_STATIC_VERSION              1100
#define IDC_BUTTON_nn1                  1100
#define IDC_BUTTON_wavepp               1101
#define IDC_BUTTON_wavep                1102
#define IDC_BUTTON_wavenn               1103
#define IDC_BUTTON_waven                1104
#define IDC_BUTTON_nn2                  1105
#define IDC_BUTTON_nn3                  1106
#define IDC_BUTTON_nn4                  1107
#define IDC_BUTTON_nn5                  1108
#define IDC_BUTTON_nn6                  1109
#define IDC_STATIC_T1                   1110
#define IDC_BUTTON_nn7                  1112
#define IDC_BUTTON_nn8                  1113
#define IDC_STATIC_T2                   1114
#define IDC_STATIC_T3                   1115
#define IDC_STATIC_T4                   1116
#define IDC_STATIC_T5                   1117
#define IDC_STATIC_T6                   1118
#define IDC_STATIC_T7                   1119
#define IDC_LIST_MSG                    1120
#define IDC_BUTTON_IOSTATUS             1121
#define IDC_STATIC_T8                   1122
#define IDC_BUTTON1                     1122
#define IDC_CHECK_PLUS                  1123
#define IDC_STATIC_DI1                  1124
#define IDC_STATIC_DI2                  1125
#define IDC_BUTTON2                     1126
#define IDC_BUTTON3                     1127
#define IDC_BUTTON4                     1128
#define IDC_BUTTON5                     1129
#define IDC_BUTTON6                     1130
#define IDC_STATIC_DI3                  1131
#define IDC_STATIC_DI4                  1132
#define IDC_STATIC_DI5                  1133
#define IDC_BUTTON7                     1134
#define IDC_BUTTON8                     1135
#define IDC_STATIC_DI6                  1136
#define IDC_STATIC_DI7                  1137
#define IDC_STATIC_DI8                  1138
#define IDC_STATIC_MSG                  1140
#define IDC_LIST_REPORT                 1141
#define IDC_BUTTON_EXCEL                1142
#define IDC_CHECK1                      1143
#define IDC_CHECK2                      1144
#define IDC_BUTTON_SPRENT               1144
#define IDC_CHECK3                      1145
#define IDC_EDIT_SPEED                  1145
#define IDC_CHECK4                      1146
#define IDC_EDIT_SID                    1146
#define IDC_CHECK5                      1148
#define IDC_CHECK6                      1149
#define IDC_EDIT_PLY                    1149
#define IDC_CHECK7                      1150
#define IDC_EDIT_STEEL                  1150
#define IDC_CHECK8                      1151
#define IDC_EDIT_GUIGE                  1151
#define IDC_EDIT_CURRENTPLY             1152
#define IDC_STATIC_CURRENTPLY           1153
#define IDC_STATIC9                     1154
#define IDC_STATIC_POSITION             1155
#define IDC_EDIT_POSITION               1156
#define IDC_EDIT_MINPLY                 1157
#define IDC_STATIC_MINPLY               1158
#define IDC_BUTTON_PRINTALL             1159
#define IDC_BUTTON_PRINTCURRENT         1160
#define IDC_BUTTON_UPPAGE               1161
#define IDC_BUTTON_NEXTPAGE             1162
#define IDC_STATIC_LEN                  1163
#define IDC_EDIT_menxian                1164
#define IDC_BUTTON_1                    1165
#define IDC_BUTTON_H                    1165
#define IDC_BUTTON_2                    1166
#define IDC_BUTTON_Z                    1166
#define IDC_STATIC_HALF                 1166
#define IDC_STATIC_STEP                 1167
#define IDC_STATIC_HACC                 1168
#define IDC_STATIC_VACC                 1169
#define IDC_EDIT_                       1170
#define IDC_COMBO_HACC                  1171
#define IDC_COMBO_VACC                  1172
#define IDC_CHECK_JPG                   1173
#define INTIAL_SET                      32771
#define PAR_SET                         32772
#define NET_SET                         32773
#define ID_MENUITEM32775                32775
#define ID_MENUITEM_NETSET              32775
#define DATABASE_SET                    32776
#define ID_MENUITEM32778                32778
#define ID_MENUITEM_DATABASESET         32778
#define CARD_SET                        32779
#define MIAN                            32780
#define ID_MENUITEM_NEXTC               32781
#define ID_MENUITEM_PREC                32782
#define ID_MENUITEM_FIRSTC              32783
#define ID_MENUITEM_CHSET               32784
#define ID_MENUITEM_THRCH               32785
#define ID_MENUITEM32786                32786
#define ID_SIMPLE                       32788
#define ID_COMBINE                      32789
#define IDC_FAULT                       32790
#define ID_DIFFER                       32791
#define ID_PHASE                        32792
#define ID_PLY                          32793
#define ID_DIFFERENCE                   32794
#define ID_ThickPipe                    32795

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1174
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
